image: Visual Studio 2019

build:
  verbosity: detailed

cache:
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

install:
  - dotnet tool restore

build_script:
  - cmd: dotnet fake build -t CiBuild

artifacts:
  - path: 'dist\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: PzxDJoHZvrDclC7ca+kbbN6JU27UAGeqZmZwgQvb3c/xXIa1w/e1hX4qs5iu/233
    on:
      appveyor_repo_tag: true
